### ISSUE TITLE
Widget base currency choice

### ISSUE THREAD

**Issue by tillycatcat** [mezhevikin/converter-help#5]
Hi, great app! 

Would it be possible to add an option to choose what you want your base currency to be for the widget. 

For example, my iPhone region is UK, but if I wanted USD as the base currency to convert from, I can’t see an option to do that.

thanks!

**Comment by mezhevikin** [comment]
Hi, I am working on a new version of the converter that includes this option. It will be a separate application because it has a minimum target iOS 17. Unfortunately, I can't provide you with a release date, but I hope it will be soon. If you're interested, you can give me your email, and I will send you the link.

**Comment by mezhevikin** [comment]
You can change widget currency in Neo Converter - https://apps.apple.com/us/app/id6477806343


![4](https://github.com/mezhevikin/converter-help/assets/973364/fedd2188-008e-4c9f-8062-6baaf8ab5a9b)
